stages:
- name: build and push docker image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: ${CICD_GIT_REPO_NAME}/${CICD_GIT_REPO_NAME}:${CICD_GIT_BRANCH}-${CICD_GIT_COMMIT}
      pushRemote: true
      registry: harbor-demo.iiidevops.org
    env:
      PLUGIN_BUILD_ARGS: --progress=tty --network=host
      PLUGIN_DEBUG: "true"
      PLUGIN_INSECURE: "true"
      PLUGIN_MIRROR: https://harbor-demo.iiidevops.org
      PLUGIN_MTU: "1000"
    when:
      branch:
        include:
        - master
        - develop
- name: Deploy app-web
  steps:
  - applyAppConfig:
      catalogTemplate: cattle-global-data:iii-dev-charts3-web
      version: 0.3.0
      name: ${CICD_GIT_REPO_NAME}-${CICD_GIT_BRANCH}-serv
      targetNamespace: ${CICD_GIT_REPO_NAME}
      answers:
        pipeline.sequence: ${CICD_EXECUTION_SEQUENCE}
        harbor.host: harbor-demo.iiidevops.org
        git.url: ${CICD_GIT_URL}
        git.branch: ${CICD_GIT_BRANCH}
        git.commitID: ${CICD_GIT_COMMIT}
        git.repoName: ${CICD_GIT_REPO_NAME}
        web.port: 80
        web.imageTag: ${CICD_GIT_REPO_NAME}/${CICD_GIT_BRANCH}:latest
        newman.enabled: false
        newman.runnerVersion: 2.0.1
        webinspect.enabled: true
        webinspect.runnerVersion: 1.1.0
        ingress.externalHost: ingress-demo.iiidevops.org
    when:
      branch:
        include:
        - master
        - develop
