stages:
- name: build and push docker image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: ${CICD_GIT_REPO_NAME}/${CICD_GIT_REPO_NAME}:${CICD_GIT_BRANCH}-${CICD_GIT_COMMIT}
      pushRemote: true
      registry: harbor-demo.iiidevops.org
    env:
      PLUGIN_BUILD_ARGS: --progress=tty --network=host
      PLUGIN_DEBUG: "true"
      PLUGIN_INSECURE: "true"
      PLUGIN_MIRROR: https://harbor-demo.iiidevops.org
      PLUGIN_MTU: "1000"
    when:
      branch:
        include:
        - master
        - develop
- name: Deploy app-web
  steps:
  - applyAppConfig:
      catalogTemplate: cattle-global-data:iii-dev-charts3-web
      version: 0.2.1
      answers:
        git.branch: ${CICD_GIT_BRANCH}
        git.commitID: ${CICD_GIT_COMMIT}
        git.host: gitlab-demo.iiidevops.org
        git.repoName: ${CICD_GIT_REPO_NAME}
        git.url: ${CICD_GIT_URL}
        harbor.host: harbor-demo.iiidevops.org
        newman.enabled: "false"
        pipeline.sequence: ${CICD_EXECUTION_SEQUENCE}
        web.image: ${CICD_GIT_REPO_NAME}/${CICD_GIT_REPO_NAME}
        web.tag: ${CICD_GIT_BRANCH}-${CICD_GIT_COMMIT}
        web.type: php
        xip.ip: 10.20.0.77
      name: ${CICD_GIT_REPO_NAME}-${CICD_GIT_BRANCH}-web
      targetNamespace: ${CICD_GIT_REPO_NAME}
    when:
      branch:
        include:
        - master
        - develop
